INSERT INTO lab_test_catalog (test_code, test_name, description, sample_type, normal_range, unit, price) VALUES
('CBC', 'Complete Blood Count', 'Measures different components of blood', 'BLOOD', NULL, NULL, 25.00),
('WBC', 'White Blood Cell Count', 'Counts white blood cells', 'BLOOD', '4500-11000', 'cells/mcL', 15.00),
('RBC', 'Red Blood Cell Count', 'Counts red blood cells', 'BLOOD', '4.5-5.5', 'million/mcL', 15.00),
('HGB', 'Hemoglobin', 'Measures hemoglobin in blood', 'BLOOD', '12.0-17.5', 'g/dL', 12.00),
('HCT', 'Hematocrit', 'Percentage of blood volume occupied by RBCs', 'BLOOD', '36-51', '%', 12.00),
('PLT', 'Platelet Count', 'Counts platelets', 'BLOOD', '150000-400000', 'cells/mcL', 15.00),
('BMP', 'Basic Metabolic Panel', 'Tests blood sugar, calcium, and electrolytes', 'BLOOD', NULL, NULL, 35.00),
('GLU', 'Glucose (Fasting)', 'Measures fasting blood sugar', 'BLOOD', '70-100', 'mg/dL', 10.00),
('BUN', 'Blood Urea Nitrogen', 'Measures kidney function', 'BLOOD', '7-20', 'mg/dL', 12.00),
('CRE', 'Creatinine', 'Measures kidney function', 'BLOOD', '0.7-1.3', 'mg/dL', 12.00),
('NA', 'Sodium', 'Measures sodium level', 'BLOOD', '136-145', 'mEq/L', 10.00),
('K', 'Potassium', 'Measures potassium level', 'BLOOD', '3.5-5.0', 'mEq/L', 10.00),
('CL', 'Chloride', 'Measures chloride level', 'BLOOD', '98-106', 'mEq/L', 10.00),
('CO2', 'Carbon Dioxide', 'Measures CO2 in blood', 'BLOOD', '23-29', 'mEq/L', 10.00),
('CA', 'Calcium', 'Measures calcium level', 'BLOOD', '8.5-10.5', 'mg/dL', 10.00),
('LIP', 'Lipid Panel', 'Complete cholesterol test', 'BLOOD', NULL, NULL, 40.00),
('TC', 'Total Cholesterol', 'Measures total cholesterol', 'BLOOD', '0-200', 'mg/dL', 15.00),
('HDL', 'HDL Cholesterol', 'Measures good cholesterol', 'BLOOD', '40-60', 'mg/dL', 15.00),
('LDL', 'LDL Cholesterol', 'Measures bad cholesterol', 'BLOOD', '0-100', 'mg/dL', 15.00),
('TG', 'Triglycerides', 'Measures triglycerides', 'BLOOD', '0-150', 'mg/dL', 15.00),
('TSH', 'Thyroid Stimulating Hormone', 'Measures thyroid function', 'BLOOD', '0.4-4.0', 'mIU/L', 30.00),
('T4', 'Thyroxine (T4)', 'Measures thyroid hormone', 'BLOOD', '5.0-12.0', 'mcg/dL', 25.00),
('HBA1C', 'Hemoglobin A1C', 'Average blood sugar over 3 months', 'BLOOD', '4.0-5.6', '%', 30.00),
('UA', 'Urinalysis', 'Analyzes urine composition', 'URINE', NULL, NULL, 20.00),
('UCG', 'Urine Culture', 'Tests for bacteria in urine', 'URINE', 'No growth', NULL, 35.00),
('LFT', 'Liver Function Test', 'Tests liver enzymes', 'BLOOD', NULL, NULL, 35.00),
('ALT', 'Alanine Aminotransferase', 'Liver enzyme', 'BLOOD', '7-56', 'U/L', 12.00),
('AST', 'Aspartate Aminotransferase', 'Liver enzyme', 'BLOOD', '10-40', 'U/L', 12.00),
('ALP', 'Alkaline Phosphatase', 'Liver/bone enzyme', 'BLOOD', '44-147', 'U/L', 12.00),
('ESR', 'Erythrocyte Sedimentation Rate', 'Measures inflammation', 'BLOOD', '0-20', 'mm/hr', 15.00);
